[project]
name = "QAnon-Conspiracy"
version = "0.0.1"
description = "A description of your project"
authors = ["Sigurður Detlef Jónsson", "sdj29@hi.is","Óskar Guðmundur Kristinsson","ogk2@hi.is"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tool.pixi.pypi-dependencies]
probs = { path = ".", editable = true }


[dependencies]
python = ">=3.7.12,<4"
tensorflow = ">=1.14.0,<3"
numpy = ">=1.19.5,<2"
scipy = ">=1.7.3,<2"
matplotlib = ">=3.5.3,<4"
keras = ">=2.3.1,<3"
seaborn = ">=0.12.2,<0.13"
nltk = ">=3.8.1,<4"
notebook = ">=6.5.7,<8"
pandas = ">=1.3.5,<3"
